name: wario
description: A multi-repo management mammer jammer.
version: 0.1.0
author: Justin Beckwith <justin.beckwith@gmail.com>
homepage: https://github.com/JustinBeckwith/wario
dependencies:
  args: "^1.6.0"
  http: "^0.12.1"
  json_object_lite: ^2.1.1
  colorize: "^2.0.0"
  github: "^6.0.0"
executables:
  wario: wario
environment:
  sdk: ">=2.8.0"
