name: wario
description: A multi-repo management mammer jammer.
version: 0.1.0
homepage: https://github.com/JustinBeckwith/wario
dependencies:
  args: "^1.6.0"
  http: "^0.12.1"
  colorize: "^2.0.0"
dev_dependencies:
  test: ^1.14.3
  nock: ^1.0.2
executables:
  wario: wario
environment:
  sdk: ">=2.0.0 <3.0.0"
