on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart --version
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed bin lib test
      - run: dart analyze
      - run: dart test -r expanded
