on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - run: dart --version
      - run: pub get
      - run: pub run test
